//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirius.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Dispositivo
    {

        public int id { get; set; }
        public string SSE { get; set; }
        public string plant { get; set; }
        public string device { get; set; }
        public string subsystem { get; set; }
        public string section { get; set; }
        public string model { get; set; }
        public string serial { get; set; }
        public Nullable<double> altitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> year { get; set; }
        public string deviceType { get; set; }
        public string up { get; set; }
        public string ecName { get; set; }
        public string notes { get; set; }
        public string vendor { get; set; }
        public string downtimeClass { get; set; }
        public Nullable<double> nominalPower { get; set; }


        [ForeignKey("Dispositivoid")]
        public ICollection<DettagliDispositivo> DettagliDispositivos { get; set; }

    }
}
